<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { Search, Sparkles, ShieldAlert, GitBranch } from 'lucide-vue-next'
import { k8sService } from '../../services/k8sService'
import YamlInspector from '../../components/YamlInspector.vue'
import type { AttachmentType, IAMSecurityPrincipalGroup, IAMSecurityRecord } from './types'

type DetailTab = 'map' | 'yaml'

const iamRecords = ref<IAMSecurityRecord[]>([])
const isLoading = ref(false)
const searchQuery = ref('')
const selectedRoleKey = ref('')
const selectedSubject = ref('')
const detailTab = ref<DetailTab>('map')

const getRoleKey = (arn: string): string => {
  const chunks = arn.split('/')
  const raw = chunks[chunks.length - 1] || arn
  return raw.trim().toLowerCase()
}

const truncateArn = (arn: string): string => {
  if (arn.length <= 72) return arn
  return `${arn.slice(0, 38)}...${arn.slice(-28)}`
}

const attachmentClass = (type: AttachmentType): string => {
  if (type === 'IRSA') return 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
  if (type === 'PodIdentity') return 'bg-sky-500/20 text-sky-300 border-sky-500/40'
  return 'bg-violet-500/20 text-violet-300 border-violet-500/40'
}

const groupedPrincipals = computed<IAMSecurityPrincipalGroup[]>(() => {
  const grouped = new Map<string, IAMSecurityPrincipalGroup>()

  for (const record of iamRecords.value) {
    const existing = grouped.get(record.iam_principal)
    if (!existing) {
      grouped.set(record.iam_principal, {
        iamPrincipal: record.iam_principal,
        roleKey: getRoleKey(record.iam_principal),
        attachments: [record.attachment_type],
        records: [record],
      })
      continue
    }

    existing.records.push(record)
    if (!existing.attachments.includes(record.attachment_type)) {
      existing.attachments.push(record.attachment_type)
    }
  }

  return Array.from(grouped.values()).sort((a, b) => a.roleKey.localeCompare(b.roleKey))
})

const filteredPrincipals = computed<IAMSecurityPrincipalGroup[]>(() => {
  const query = searchQuery.value.trim().toLowerCase()
  if (!query) return groupedPrincipals.value

  return groupedPrincipals.value.filter((group) => {
    if (group.iamPrincipal.toLowerCase().includes(query)) return true
    if (group.roleKey.includes(query)) return true
    return group.records.some((record) => record.k8s_subject.toLowerCase().includes(query))
  })
})

const selectedGroup = computed<IAMSecurityPrincipalGroup | null>(() => {
  if (filteredPrincipals.value.length === 0) return null
  const found = filteredPrincipals.value.find((group) => group.roleKey === selectedRoleKey.value)
  return found || filteredPrincipals.value[0]
})

const uniqueSubjects = computed<string[]>(() => {
  if (!selectedGroup.value) return []
  const seen = new Set<string>()
  for (const record of selectedGroup.value.records) {
    seen.add(record.k8s_subject)
  }
  return Array.from(seen.values()).sort()
})

const selectedRecords = computed<IAMSecurityRecord[]>(() => {
  if (!selectedGroup.value) return []
  if (!selectedSubject.value) return selectedGroup.value.records
  return selectedGroup.value.records.filter((record) => record.k8s_subject === selectedSubject.value)
})

const selectedSummary = computed<string>(() => {
  const candidate = selectedRecords.value.find((record) => record.summary_placeholder.trim().length > 0)
  return candidate?.summary_placeholder || 'Summary will be generated by AI in a future release.'
})

const inspectorItem = computed(() => {
  if (!selectedGroup.value) return null

  const allYamls: Array<{ kind: string; name: string; data: string; namespace: string }> = []

  for (const record of selectedRecords.value) {
    for (const detail of record.rbac_details) {
      allYamls.push({
        kind: detail.binding_kind,
        name: detail.binding_name,
        data: detail.binding_yaml,
        namespace: detail.binding_namespace || 'Cluster-Wide',
      })
      allYamls.push({
        kind: detail.role_kind,
        name: detail.role_name,
        data: detail.role_yaml,
        namespace: detail.role_namespace || 'Cluster-Wide',
      })
    }
  }

  return {
    name: selectedGroup.value.iamPrincipal,
    all_yamls: allYamls,
  }
})

const updateURL = (roleKey: string) => {
  if (!roleKey) return
  const url = new URL(window.location.href)
  url.pathname = '/iam-security'
  url.searchParams.set('role', roleKey)
  window.history.replaceState({}, '', `${url.pathname}${url.search}`)
}

const parseRoleFromURL = (): string => {
  const url = new URL(window.location.href)
  return (url.searchParams.get('role') || '').trim().toLowerCase()
}

const fetchIAMSecurity = async (refresh = false) => {
  isLoading.value = true
  try {
    const data = await k8sService.fetchTableData('iam', refresh)
    iamRecords.value = Array.isArray(data) ? data : []
  } catch (err) {
    console.error('IAM security fetch failed:', err)
    iamRecords.value = []
  } finally {
    isLoading.value = false
  }
}

const selectPrincipal = (group: IAMSecurityPrincipalGroup) => {
  selectedRoleKey.value = group.roleKey
}

watch(selectedGroup, (group) => {
  if (!group) return
  selectedRoleKey.value = group.roleKey
  if (!uniqueSubjects.value.includes(selectedSubject.value)) {
    selectedSubject.value = uniqueSubjects.value[0] || ''
  }
  updateURL(group.roleKey)
})

watch(filteredPrincipals, (groups) => {
  if (groups.length === 0) {
    selectedRoleKey.value = ''
    selectedSubject.value = ''
  }
})

onMounted(async () => {
  selectedRoleKey.value = parseRoleFromURL()
  await fetchIAMSecurity(false)
})
</script>

<template>
  <div class="h-full flex flex-col">
    <div class="workspace-toolbar">
      <div class="relative flex-1 max-w-2xl">
        <Search class="absolute left-4 top-3 text-slate-500" :size="18" />
        <input
          v-model="searchQuery"
          type="text"
          placeholder="Search IAM Role or K8s Subject..."
          class="w-full bg-slate-900/40 border border-white/10 rounded-2xl pl-12 pr-4 py-3 text-sm text-slate-200 outline-none focus:border-blue-500/50"
        />
      </div>
    </div>

    <main class="workspace-main">
      <div class="workspace-split">
      <section class="workspace-list-pane custom-scroll p-4">
        <div v-if="isLoading" class="space-y-3">
          <div v-for="idx in 7" :key="idx" class="workspace-card animate-pulse">
            <div class="h-3 bg-slate-700/50 rounded w-3/4 mb-3"></div>
            <div class="h-2 bg-slate-800/80 rounded w-1/2"></div>
          </div>
        </div>

        <template v-else>
          <button
            v-for="group in filteredPrincipals"
            :key="group.iamPrincipal"
            @click="selectPrincipal(group)"
            :class="selectedGroup?.iamPrincipal === group.iamPrincipal
              ? 'border-blue-500/50 bg-blue-500/10 ring-1 ring-blue-500/20'
              : 'border-white/10 bg-slate-900/25 hover:bg-slate-900/45'"
            class="w-full text-left p-4 rounded-2xl border transition-all mb-3"
          >
            <p class="font-mono text-[11px] text-slate-100 truncate" :title="group.iamPrincipal">
              {{ truncateArn(group.iamPrincipal) }}
            </p>
            <div class="mt-3 flex flex-wrap gap-2">
              <span
                v-for="attachment in group.attachments"
                :key="attachment"
                :class="attachmentClass(attachment)"
                class="text-[9px] px-2 py-1 rounded-full border font-black tracking-wide uppercase"
              >
                {{ attachment }}
              </span>
            </div>
          </button>

          <div v-if="filteredPrincipals.length === 0" class="text-center text-slate-500 pt-20">
            No IAM identities matched your filter.
          </div>
        </template>
      </section>

      <section class="workspace-detail-pane overflow-y-auto custom-scroll">
        <div v-if="!selectedGroup && !isLoading" class="h-full flex flex-col items-center justify-center text-slate-500">
          <div class="p-6 rounded-full bg-slate-800/30 border border-white/10 mb-4">
            <ShieldAlert :size="36" />
          </div>
          <p class="text-sm">Select an IAM identity to begin</p>
        </div>

        <div v-else class="space-y-5 p-5">
          <header class="workspace-card">
            <h2 class="text-lg text-white font-bold tracking-tight break-all">
              {{ selectedGroup?.iamPrincipal }} -> {{ selectedSubject || 'K8s Subject' }}
            </h2>
            <div class="mt-3 flex flex-wrap gap-2">
              <button
                v-for="subject in uniqueSubjects"
                :key="subject"
                @click="selectedSubject = subject"
                :class="selectedSubject === subject
                  ? 'chip-btn bg-blue-500/20 border-blue-500/40 text-blue-300'
                  : 'chip-btn bg-slate-900/40 border-white/10 text-slate-300'"
              >
                {{ subject }}
              </button>
            </div>
          </header>

          <div class="insight-card">
            <div class="flex items-center gap-2 text-[10px] font-black tracking-widest uppercase text-indigo-200 mb-2">
              <Sparkles :size="12" /> AI Security Insight
            </div>
            <p class="text-sm text-slate-200 leading-relaxed">
              {{ selectedSummary }}
            </p>
          </div>

          <div class="rounded-2xl border border-white/10 bg-slate-900/30 overflow-hidden">
            <div class="flex border-b border-white/10 bg-slate-900/40">
              <button
                @click="detailTab = 'map'"
                :class="detailTab === 'map' ? 'detail-tab-btn text-blue-300 border-b-2 border-blue-400' : 'detail-tab-btn text-slate-400'"
              >
                Visual Map
              </button>
              <button
                @click="detailTab = 'yaml'"
                :class="detailTab === 'yaml' ? 'detail-tab-btn text-blue-300 border-b-2 border-blue-400' : 'detail-tab-btn text-slate-400'"
              >
                YAML Inspector
              </button>
            </div>

            <div class="p-4 bg-slate-900/20">
              <div v-if="detailTab === 'map'" class="space-y-3">
                <div
                  v-for="record in selectedRecords"
                  :key="`${record.attachment_type}-${record.k8s_subject}`"
                  class="workspace-card"
                >
                  <div class="text-[11px] text-slate-100 font-mono break-all">
                    {{ record.iam_principal }}
                  </div>
                  <div class="mt-2 flex items-center gap-2 text-xs text-slate-400">
                    <GitBranch :size="14" class="text-blue-400" />
                    <span>{{ record.attachment_type }}</span>
                    <span class="text-slate-600">-></span>
                    <span class="text-blue-300">{{ record.k8s_subject }}</span>
                    <span class="text-slate-600">-></span>
                    <span>{{ record.rbac_details.length }} RBAC links</span>
                  </div>
                </div>
              </div>

              <YamlInspector v-else :item="inspectorItem" :isLoading="isLoading" />
            </div>
          </div>
        </div>
      </section>
      </div>
    </main>
  </div>
</template>
